board/raspberrypi: repair /boot filesystem at startup
This repairs the autoboot.txt FAT filesystem at startup by setting the
passno to prevent to the /boot mountpoint to be mounted as read-only
(i.e. not writable, as RAUC requires it to write its persistent files;
the data-directory in /etc/rauc/system.conf).

See:

	[    7.352259] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.

Fixes:

	# rauc install /tmp/buildroot.raucb
	installing
	  0% Installing
	  0% Determining slot states
	 10% Determining slot states done.
	 10% Checking bundle
	 10% Verifying signature
	 20% Verifying signature done.
	[   70.637124] loop0: detected capacity change from 0 to 100658
	 20% Checking bundle done.
	[   70.662763] loop0: detected capacity change from 100658 to 100656
	[   70.722929] squashfs: version 4.0 (2009/01/31) Phillip Lougher
	 20% Checking manifest contents
	 30% Checking manifest contents done.
	 30% Determining target install group
	 40% Determining target install group done.
	 40% Updating slots
	 40% Checking slot rootfs.0
	 43% Checking slot rootfs.0 failed.
	 99% Updating slots failed.
	100% Installing failed.
	LastError: Installation error: Error while writing status file: Failed to create file ?/boot/rauc/central.raucs.QTGJ02?: Read-only file system
	Installing `/tmp/buildroot.raucb` failed